name: â¯ release

on: [push, pull_request]

jobs:
  mini_functions_release:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry ğŸ§‘â€ğŸ’¼
        id: cache-cargo-registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build ğŸš€
        id: cache-cargo-build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Toolchain ğŸ› 
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build libraries ğŸ—
        run: |
          cargo install cross
          cargo clean
          cross build --release --target=${{ matrix.target }} --lib
      - name: Cache build artifacts ğŸ§‘â€ğŸ’¼
        id: cache-build-artifacts
        uses: actions/cache@v2
        with:
          path: target/${{ matrix.target }}/release
          key: ${{ runner.os }}-cargo-build-target-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Test ğŸ§ª
        id: test
        run: |
          cargo test --all

      - name: Package ğŸ“¦
        id: package
        run: |
          version=$(grep version Cargo.toml | sed -n 2p | cut -d '"' -f 2)
          echo "version=$version"
          mkdir -p packages
          mv target/${{ matrix.target }}/release/libmini_functions.rlib packages/libmini_functions-0.0.7.rlib
          tar -czvf packages/mini_functions-0.0.7.tar.gz packages/libmini_functions-0.0.7.rlib

      - name: Checkout ğŸ›’
        id: checkout
        uses: actions/checkout@v3

      - name: Generate Changelog ğŸ“œ
        id: changelog
        run: |

          # Generate the release notes template
          echo "<img src=\"https://raw.githubusercontent.com/sebastienrousseau/vault/main/assets/shields/made-with-love.svg\" alt=\"Made with Love\"/><br>" > ${{ github.workspace }}-CHANGELOG.md
          echo "<h1>Highly performant utility and wrapper functions library for Rust ğŸš€</h1><br>" > ${{ github.workspace }}-CHANGELOG.md
          echo "<img src=\"https://raw.githubusercontent.com/sebastienrousseau/vault/main/assets/banners/banner-mini-functions.svg\" alt=\"Mini Functions Banner\" width=\"100%\"/><br>" > ${{ github.workspace }}-CHANGELOG.md
          echo "<h2>Welcome to Mini Functions ğŸ‘‹</h2><br>" >> ${{ github.workspace }}-CHANGELOG.md
          echo "Mini Functions is a highly performant utility and wrapper functions library for Rust that has been carefully designed with optimization and efficiency in mind.<br>" >> ${{ github.workspace }}-CHANGELOG.md
          echo "" >> ${{ github.workspace }}-CHANGELOG.md
          echo "By providing convenient wrapper functions, our library aims to provide a high-level interface for common tasks while still leveraging the performance benefits of Rust under the hood.<br>" >> ${{ github.workspace }}-CHANGELOG.md
          echo "" >> ${{ github.workspace }}-CHANGELOG.md
          echo "These utility functions serve as an essential toolkit for any Rust developer, and the library's design abstractions allow for easy integration into a variety of projects and applications." >> ${{ github.workspace }}-CHANGELOG.md
          echo "" >> ${{ github.workspace }}-CHANGELOG.md
          echo "<h2>Key Features ğŸ¯</h2><br>" >> ${{ github.workspace }}-CHANGELOG.md
          echo "" >> ${{ github.workspace }}-CHANGELOG.md

          # Generate a list of commits since the last release and add them to the release notes
          git log -50 main..feature/mini-functions --oneline | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | awk '{labels="";for(i=2;i<=NF;i++){if($i~/^[a-zA-Z]+\([a-zA-Z0-9-_]+\):/)labels=labels" "$i;else break;}printf("-%s %s\n",labels,$0);}' | sort -k1,1 >> ${{ github.workspace }}-CHANGELOG.md
          echo "" >> ${{ github.workspace }}-CHANGELOG.md

      - name: Create Release ğŸš€
        # if: github.event_name != 'pull_request'
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: ${{ github.workspace }}/packages/libmini_functions-0.0.7.tar.gz
          name: Mini Functions ğŸ¦€ v0.0.7
          tag_name: v${{ env.version }}
          release_name: Mini Functions ğŸ¦€ v0.0.7
          draft: true
          prerelease: false
