on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry ðŸ§‘â€ðŸ’¼
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build ðŸš€
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Toolchain ðŸ› 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Extract version number ðŸ“œ
        run: |
          version=$(grep version Cargo.toml | cut -d '"' -f 2)
          echo "version=$version"
      - name: Build with cross ðŸ—
        run: |
          # Build the binary
          cargo install cross
          cargo clean
          cross build --release --target=${{ matrix.target }}
      - name: Check if binary exists ðŸ“‚
        run: ls target/${{ matrix.target }}/release

      - name: Create binaries folder ðŸ“‚
        run: mkdir -p binaries

      - name: Move library ðŸšš
        run: |
          mv target/${{ matrix.target }}/release/libmini_functions.rlib binaries/libmini_functions.rlib

      - name: Rename library ðŸ“‚
        run: |
          mv binaries/libmini_functions.rlib binaries/libmini_functions-$version-${{ github.sha }}.rlib

      - name: Check if renamed binary exists ðŸ“‚
        run: |
          ls binaries

      - name: Generate Changelog ðŸ“œ
        run: |
          # Generate a changelog based on the commit history
          git log --oneline --decorate --color > changelog.txt
          # Add a header to the changelog
          echo "# Changelog" > ${{ github.workspace }}-CHANGELOG.txt
          echo >> ${{ github.workspace }}-CHANGELOG.txt
          # Append the commit history to the changelog
          cat changelog.txt >> ${{ github.workspace }}-CHANGELOG.txt

      - name: Release ðŸš€
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            binaries/libmini_functions-$version-${{ github.sha }}.rlib
          name: v$version
          tag_name: v$version
          draft: false
          prerelease: false

      - name: Create Debian package ðŸ“¦
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y debhelper fakeroot
          # Create the Debian package
          cargo deb --no-build --target=x86_64-unknown-linux-gnu

      - name: Upload binaries ðŸ“‚
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.release.upload_url }}
          asset_path: binaries/libmini_functions-$version-${{ github.sha }}.rlib
          asset_name: libmini_functions-$version-${{ matrix.target }}-${{ github.sha }}.rlib
          asset_content_type: application/octet-stream
